external_components:
  - source:
      type: git
      url: https://github.com/Csontikka/esphome-tailscale.git
      ref: main
    components: [tailscale]

time:
  - platform: sntp
    id: tailscale_time
    servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
      - 2.pool.ntp.org

binary_sensor:
  - platform: tailscale
    connected:
      name: "Tailscale Connected"
    key_expiry_warning:
      name: "Tailscale Key Expiry Warning"

text_sensor:
  - platform: tailscale
    ip_address:
      name: "Tailscale IP"
    tailscale_hostname:
      name: "Tailscale Hostname"
    memory_mode:
      name: "Tailscale Memory"
    setup_status:
      name: "Tailscale Setup Hint"
    peer_status:
      name: "Tailscale Peer Status"
    magicdns:
      name: "Tailscale MagicDNS"
    tailnet_name:
      name: "Tailscale Tailnet"
    key_expiry:
      name: "Tailscale Key Expiry"
    ha_connection_route:
      name: "HA Connection Route"

button:
  - platform: tailscale
    reconnect:
      name: "Tailscale Reconnect"
  - platform: restart
    name: "Reboot"

sensor:
  - platform: tailscale
    peers_online:
      name: "Tailscale Peers Online"
    peers_direct:
      name: "Tailscale Peers Direct"
    peers_derp:
      name: "Tailscale Peers DERP"
    peers_max:
      name: "Tailscale Peers Max"
    uptime:
      name: "Tailscale Uptime"

switch:
  - platform: tailscale
    tailscale_enabled:
      name: "Tailscale Enabled"
