esphome:
  name: esp32-tailscale
  friendly_name: "ESP32 Tailscale"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

external_components:
  - source: components

packages:
  tailscale_config: !include
    file: packages/tailscale/tailscale.yaml
    vars:
      var_tailscale_auth_key: !secret tailscale_auth_key
      var_tailscale_hostname: "esp32-tailscale"
      var_tailscale_ip: "init"  # Set to your Tailscale VPN IP after first boot
      # var_tailscale_max_peers: "16"  # Optional, default 16

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: DEBUG
  hardware_uart: UART0

api:

web_server:
  port: 80

ota:
  platform: esphome
